CREATE TABLE IF NOT EXISTS loginuser (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS foto_data (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    foto VARCHAR(255) NOT NULL,
    category ENUM('brons', 'keramiek') NOT NULL,
    titel VARCHAR(255) NOT NULL,
    afmeting_hoogte VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
